spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

springdoc.api-docs.enabled=true

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Catalog Service
springdoc.swagger-ui.urls[1].url=/catalog/v3/api-docs

springdoc.swagger-ui.urls[2].name=Order Service
springdoc.swagger-ui.urls[2].url=/orders/v3/api-docs

springdoc.swagger-ui.urls[3].name=Admin Service
springdoc.swagger-ui.urls[3].url=/admin/v3/api-docs

springdoc.swagger-ui.persist-authorization=true